apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepy-analytics
  labels:
    app: pepy-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepy-analytics
  template:
    metadata:
      labels:
        app: pepy-analytics
    spec:
      containers:
        - name: pepy-analytics
          image: ghcr.io/psincraian/pepy-analytics
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "25m"
      imagePullSecrets:
        - name: dockerconfigjson-github-com

---

apiVersion: v1
kind: Service
metadata:
  name: pepy-analytics-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: pepy-analytics
