apiVersion: batch/v1
kind: CronJob
metadata:
  name: pepy-analytics-cron
  labels:
    app: pepy-analytics-cron
spec:
  schedule: "00 08 1 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: service-account-credentials
            - name: newrelic-config
              secret:
                secretName: newrelic-config
          containers:
            - name: pepy
              image: ghcr.io/psincraian/pepy-analytics
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args:
                - -c
                - >-
                    java -Dspring.main.web-application-type=NONE -Dspring.profiles.active=cli -jar app.jar send-monthly-report &&
                    curl -fsS --retry 3 https://hc-ping.com/9ec89caf-3e01-467f-ad13-39ba6a7416cf
              resources:
                requests:
                  memory: "150Mi"
                  cpu: "150m"
                limits:
                  memory: "250Mi"
                  cpu: "200m"
          restartPolicy: Never
          imagePullSecrets:
            - name: dockerconfigjson-github-com