---

dependencies:
  - role: newrelic.newrelic-infra
    vars:
      nrinfragent_config:
        license_key: "{{ newrelic_license_key }}"
      nrinfragent_integrations:
        - name: nri-nginx
          state: latest